In [2]:
import numpy as np
a1 =  np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2.shape

(2, 3)

In [11]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,5,9]],[[1,2,3],[4,5,6]],[[7,8,9],[1,5,9]]])

In [12]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 5, 9]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 5, 9]]])

In [14]:
a3.shape
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 5, 9]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 5, 9]]])

In [15]:
a3.shape

(4, 2, 3)

In [10]:
a1.shape

(3,)

In [16]:
a3.arrays

AttributeError: 'numpy.ndarray' object has no attribute 'arrays'

In [17]:
a3.array


AttributeError: 'numpy.ndarray' object has no attribute 'array'

In [18]:
a3.ndim

3

In [19]:
a3.dtype

dtype('int64')

In [20]:
a3.size

24

In [21]:
type(a3)

numpy.ndarray

In [22]:
import pandas as pd

In [23]:
pf= pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(4, 2, 3)

In [24]:
pf = pd.DataFrame(a2)

In [25]:
pf

0  1  2
0  1  2  3
1  4  5  6